### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by jkhsjdhjs** [P2PoolOnPi/DogecoinP2PoolOnPi#1]
This is a pretty nice install script but it doesn't work anymore because github.com/blixnood/p2pool doesn't exist anymore. And using forrestv/p2pool instead won't work with dogecoin.

**Comment by PartTimeLegend** [comment]
I will look at this over the weekend. I'm not sure if there is much call for P2Pool with Dogecoin as there is now support for merged mining. I will however aim to see if I can rebuild it.

**Comment by PartTimeLegend** [comment]
As Dogecoin is not solo mined. And it's a year on. I'm closing this.

Consider this repo abandoned.
